os: linux
dist: trusty

services: docker

branches:
  only:
    - master

language: shell

## Section needed if local build
#language: android
#
#jdk: oraclejdk11
#
#android:
#    components:
#        - platform-tools
#        - build-tools-28.0.1
#        - android-28
#        - extra-android-m2repository
#        - sys-img-armeabi-v7a-android-19
#
#before_cache:
#    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
#
#cache:
#    directories:
#        - .nvm
#        - $HOME/.gradle/caches/
#        - $HOME/.gradle/wrapper/

before_install:
  - env | sort
  - export DOCKER_REPO="monogramm/ngxp-seed"
  - export API_WEB_CLIENT_ID=clientWebId
  - export API_WEB_CLIENT_SECRET=clientWebSecret
  - docker --version
  - docker-compose --version
  - docker info

install:
    # Execute CI build hooks
    # TODO Mount local dir as volume to retrieve build results
    - ./hooks/run build "${VARIANT}"

before_script:
    - docker images
#     - echo no | android create avd --force -n test -t android-19 -b armeabi-v7a
#     - emulator -avd test -no-audio -no-window &
#     - android-wait-for-emulator

script:
    # Execute CI test hooks
    - ./hooks/run test "${VARIANT}"
    # TODO Migrate android package build into Dockerfile
    # - npm run tslint
    # - npm run build.android
    # - npm run test.android --emulator --justlaunch

env: # Environments
    - VARIANT=web
    #- VARIANT=android
