os: linux
dist: trusty

services: docker

language: android

jdk: oraclejdk11

android:
    components:
        - platform-tools
        - build-tools-23.0.1
        - android-23
        - extra-android-m2repository
        - sys-img-armeabi-v7a-android-19

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

before_install:
  - env | sort
  - export home=$(pwd)
  - export TAG=travis
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export IMAGE_NAME="monogramm/docker-ngxp:${TAG}"
  - docker --version
  - docker-compose --version

install:
    # Test containers build
    - docker-compose build
    # TODO Migrate android package build into Dockerfile
    # -  install $NODE_VERSION
    # - npm cache clean
    # - npm uninstall -g @angular-cli
    # - npm install -g -f @angular-cli
    # - ng --version
    #- wget -O ./nativescript.tgz "https://s3.amazonaws.com/nativescript-ci/build_result/nativescript.tgz"
    #- npm install -g nativescript.tgz --ignore-scripts
    #- tns usage-reporting disable
    #- tns error-reporting disable
    #- npm run ngxp-install

before_script:
    - docker images
#     - echo no | android create avd --force -n test -t android-19 -b armeabi-v7a
#     - emulator -avd test -no-audio -no-window &
#     - android-wait-for-emulator

script:
    # Test containers run
    - travis_retry docker-compose -d && sleep 90
    - docker-compose ps
    #- docker-compose logs "ngxp-seed"
    #- docker-compose ps "ngxp-seed" | grep "Up"
    # TODO Migrate android package build into Dockerfile
    # - npm run tslint
    # - npm run build.android
    # - npm run test.android --emulator --justlaunch

env:
    global:
        - NODE_VERSION=12.0.5
    # Environments
