# Custom builder image
FROM monogramm/docker-ngxp:jdk AS builder

WORKDIR /usr/src/app

COPY . .

# Install NGXP project dependencies
# Build web site
RUN set -ex; \
    node --version; \
    npm --version; \
    npm run ngxp-install; \
    npm run build.android

FROM nginx:alpine

# NGINX configurations
COPY ./nginx/conf.d /etc/nginx/conf.d

# Copy built app from builder to www root
COPY --from=builder /usr/src/app/web/dist/app /usr/share/nginx/html
