# Custom builder image
FROM monogramm/docker-ngxp:jdk AS builder

WORKDIR /usr/src/app

ARG BUILD_ENV=prod
ARG CLIENT_LOCALE=en

ARG API_CLIENT_ID
ARG API_CLIENT_SECRET

COPY . .

# Install NGXP project dependencies
# Build web site
RUN set -ex; \
    node --version; \
    npm --version; \
    set +e; \
    test -n "${API_CLIENT_ID}" || exit 1; \
    test -n "${API_CLIENT_SECRET}" || exit 2; \
    set -e; \
    npm run ngxp-install; \
    sed -i \
        -e "s|  locale: '.*',|  locale: '${CLIENT_LOCALE}',|gm" \
        -e "s|  clientId: '.*',|  clientId: '${API_CLIENT_ID}',|gm" \
        -e "s|  clientSecret: '.*',|  clientSecret: '${API_CLIENT_SECRET}',|gm" \
        "web/src/environments/environment.${BUILD_ENV}.ts" \
    ; \
    npm run "build.${BUILD_ENV}"; \
    mkdir -p /usr/src/dist; \
    mv /usr/src/app/web/dist/app /usr/src/dist/app; \
    rm -rf /usr/src/app

FROM nginx:alpine

# NGINX configurations
COPY ./nginx/conf.d /etc/nginx/conf.d

# Copy built app from builder to www root
COPY --from=builder /usr/src/dist/app /var/www/html

# Arguments to label built container
ARG VCS_REF=unknown
ARG BUILD_DATE=unknown
ARG VERSION=1.1.0

ARG DOMAIN=localhost

RUN set -ex; \
    sed -i \
        -e "s|localhost|${DOMAIN}|g" \
        -e "s|lastmod>.*</lastmod|lastmod>${BUILD_DATE}</lastmod|g" \
        /var/www/html/robots.txt \
        /var/www/html/sitemap.xml \
    ; \
    echo "${TAG} ${VCS_REF} ${BUILD_DATE}" > '/var/www/html/.docker-app-version'

# Container labels (http://label-schema.org/)
# Container annotations (https://github.com/opencontainers/image-spec)
LABEL maintainer="opensource@monogramm.io" \
      product="NGXP-Seed" \
      version=$VERSION \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.vcs-url="https://github.com/Monogramm/ngxp-seed/" \
      org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.name="NGXP-Seed" \
      org.label-schema.description="Cross-platform application." \
      org.label-schema.url="https://${DOMAIN}/" \
      org.label-schema.vendor="Monogramm" \
      org.label-schema.version=$VERSION \
      org.label-schema.schema-version="1.0" \
      org.opencontainers.image.revision=$VCS_REF \
      org.opencontainers.image.source="https://github.com/Monogramm/ngxp-seed/" \
      org.opencontainers.image.created=$BUILD_DATE \
      org.opencontainers.image.title="NGXP-Seed" \
      org.opencontainers.image.description="Cross-platform application." \
      org.opencontainers.image.url="https://${DOMAIN}/" \
      org.opencontainers.image.vendor="Monogramm" \
      org.opencontainers.image.version=$VERSION \
      org.opencontainers.image.authors="opensource@monogramm.io"
