# Custom builder image
FROM monogramm/docker-ngxp:jdk AS builder

WORKDIR /usr/src/app

# Sources should be mounted to persist the built APK
#COPY . .

# Install NGXP project dependencies
# Build web site
RUN set -ex; \
    node --version; \
    npm --version; \
    npm run ngxp-install; \
    npm run build.android
