version: '2.3'

networks:
  app_external_network:
  app_internal_network:
    internal: true

services:
  app_dev_web:
    build:
      context: ./
      dockerfile: Dockerfile.develop
      #args:
      #  - PACKAGE_REPO_LOGIN=${PACKAGE_REPO_LOGIN}
      #  - PACKAGE_REPO_PASSWORD=${PACKAGE_REPO_PASSWORD}
    image: ${IMAGE_NAME:-monogramm/ngxp-seed}:develop
    #command: npm run ngxp-install && npm run start
    container_name: app_dev_web
    # [TODO] Enable auto-restart when production-ready
    #restart: always
    healthcheck:
      test: curl -f http://localhost:4200/
      interval: 1m30s
      timeout: 10s
      retries: 3
      #start_period: 40s
    ports:
      - "4200:4200"
    networks:
      - app_internal_network
      - app_external_network
    depends_on:
      app_dev_backend:
        condition: service_started
    volumes:
      # For DEV, mount local sources
      - ./:/usr/src/app

  app_dev_backend:
    image: monogramm/spring-rest-api-starter:latest
    container_name: app_dev_backend
    # [TODO] Enable auto-restart when production-ready
    #restart: always
    healthcheck:
      test: CMD curl -v --silent http://localhost:${APP_SERVER_PORT}/${APP_SERVER_CONTEXT_PATH}/health 2>&1 | grep UP
      interval: 1m30s
      timeout: 10s
      retries: 3
      #start_period: 40s
    ports:
      - "8081:${APP_SERVER_PORT}"
    networks:
      - app_internal_network
      - app_external_network
    depends_on:
      - app_dev_db
      - app_dev_mailer
    volumes:
      - ${APP_HOME}_dev/backend/logs:/srv/app/logs
      - ${APP_HOME}_dev/backend/keys:/srv/app/keys
      - ${APP_HOME}_dev/backend/config:/srv/app/config
      - ${APP_HOME}_dev/backend/data:/srv/app/data
      # If you want, you can sync time & timezone with host
      #- /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      # Application configuration
      - APP_SERVER_PORT=${APP_SERVER_PORT}
      - APP_SERVER_CONTEXT_PATH=/${APP_SERVER_CONTEXT_PATH}
      - APP_TITLE=${APP_TITLE}
      - APP_DOMAIN_NAME=${APP_DOMAIN_NAME}
      - APP_ADMIN_PASSWORD=${APP_ADMIN_PASSWORD}
      - APP_SIGNING_KEY=
      - APP_SIGNING_KEYPAIR_PASS=${APP_SIGNING_KEYPAIR_PASS}
      - APP_DEMO_DATA=true
      # Database configuration (PostgreSQL)
      - DB_PLATFORM=postgresql
      - DB_HOST=app_dev_db
      - DB_NAME=${APP_DB_NAME}
      - DB_USER=${APP_DB_USER}
      - DB_PASSWORD=${APP_DB_PASSWORD}
      # Mail configuration
      - MAIL_HOST=app_dev_mailer
      - MAIL_PORT=1025
      - MAIL_PROTOCOL=smtp
      - MAIL_USER=${APP_SMTP_USER}
      - MAIL_PASSWORD=${APP_SMTP_PASSWD}
      - MAIL_SSL=false
      - MAIL_STARTTLS=false
      # Wait for it...
      - WAIT_FOR=app_dev_db:5432

  app_dev_db:
    image: postgres:10-alpine
    container_name: app_dev_db
    restart: always
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${APP_DB_USER}"]
    expose:
      - '5432'
    ports:
      - "55432:5432"
    networks:
      - app_internal_network
    volumes:
      - /srv/spring_rest_api_starter/postgres/data:/var/lib/postgresql/data
      # If you want, you can sync time & timezone with host
      #- /etc/localtime:/etc/localtime:ro
      #- /etc/timezone:/etc/timezone:ro
    environment:
      - POSTGRES_DB=${APP_DB_NAME}
      - POSTGRES_USER=${APP_DB_USER}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD}

  # Test services (do not use in production)

  app_dev_mailer:
    image: sj26/mailcatcher:latest
    hostname: app_dev_mailer
    container_name: app_dev_mailer
    restart: always
    expose:
      - '1025'
    ports:
      - "1080:1080"
    networks:
      - app_internal_network
      - app_external_network
    # If you want, you can sync time & timezone with host
    #volumes:
    #  - /etc/localtime:/etc/localtime:ro
    #  - /etc/timezone:/etc/timezone:ro
