version: "2"
services:
  ngxp-seed:
    build: .
    image: ngxp-seed
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      # Mount local dir to build from sources
      - .:/src
      - ./nginx/keys/:/etc/nginx/keys
